name: Docs
on: [push, pull_request, workflow_dispatch]


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/_build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        
        with:
          path: docs/_build
          retention-days: 90
  
  deploy-docs:
    needs: build-docs
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
      
    concurrency: 
      group: "pages"
      cancel-in-progress: true
    
    runs-on: ubuntu-latest
    steps:
     - name: Deploy artifact to GitHub Pages
       id: deployment
       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
       uses: actions/deploy-pages@v1
         
